## Testing if GitHub ipynb files can be opened in Google Colab

In [2]:
import numpy as np

a = np.linspace(1, 10, 10)
print(a)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [4]:
b = np.array([range(11, 26)]).reshape((3,5))
print(b)

[[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [4]:
print(a.dtype)
print(a.shape)
print(a.size)
print(a.ndim)

float64
(10,)
10
1


In [5]:
print(b.dtype)
print(b.shape)
print(b.size)
print(b.ndim)

int32
(3, 5)
15
2
