<a href="https://colab.research.google.com/github/ganeshbmc/Hackerrank/blob/Hackerrank/colab%20and%20github.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Testing if GitHub ipynb files can be opened in Google Colab

In [ ]:
import numpy as np

a = np.linspace(1, 10, 10)
print(a)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [ ]:
b = np.array([range(11, 26)]).reshape((3,5))
print(b)

[[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [ ]:
print(a.dtype)
print(a.shape)
print(a.size)
print(a.ndim)

float64
(10,)
10
1


In [ ]:
print(b.dtype)
print(b.shape)
print(b.size)
print(b.ndim)

int32
(3, 5)
15
2


## This is fun!
## Lemme try adding a link to colab on github repo